# Generated by Django 4.1.4 on 2023-10-30 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_book_author_name_alter_book_book_add_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_add_date",
            field=models.DateField(default=datetime.date(2023, 10, 30)),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_add_time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 10, 30, 12, 6, 12, 21983, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="issueditem",
            name="issue_date",
            field=models.DateField(default=datetime.date(2023, 10, 30)),
        ),
    ]
